[workspace]
resolver = "2"
members = [
    "crates/redunar-capture",
    "crates/redunar-capture-audio",
    "crates/redunar-capture-kms",
    "crates/redunar-capture-opengl",
    "crates/redunar-capture-vulkan",
    "crates/redunar-core",
    "crates/redunar-platform",
    "crates/redunar-daemon",
    "crates/redunar-hotkeys",
    "crates/redunar-nvidia-nvml",
]

[workspace.package]
version = "0.1.4"
edition = "2024"
license = "GPL-3.0-or-later"
rust-version = "1.97"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
