//! Bounded, versioned local protocol shared by Redunar capture producers and
//! the daemon. The wire format deliberately carries no paths, game names, or
//! user data; it only identifies one daemon-created session and its timings.

mod overlay;

pub use overlay::{
    OVERLAY_HARDWARE_TELEMETRY_BYTES, OverlayHardwareTelemetry, OverlayTelemetryError,
    REPLAY_MENU_TELEMETRY_BYTES, REPLAY_SHORTCUT_LABEL_BYTES, ReplayMenuStatus,
    ReplayMenuTelemetry, ReplayShortcutLabel, decode_overlay_hardware_telemetry,
    decode_replay_menu_telemetry, encode_overlay_hardware_telemetry, encode_replay_menu_telemetry,
};

use std::error::Error;
use std::fmt;

pub const PROTOCOL_VERSION: u16 = 5;
pub const MAX_FRAME_INTERVALS: usize = 128;
pub const MAX_REPLAY_SOURCE_WIDTH: u32 = 3_840;
pub const MAX_REPLAY_SOURCE_HEIGHT: u32 = 2_160;
/// Shared bounded depth of Replay's asynchronous conversion/encode pipeline.
pub const REPLAY_ENCODER_PIPELINE_DEPTH: usize = 4;
/// Producer exports need one handoff beyond encoder depth so the submission
/// that recycles slot zero can arrive and release the oldest DMA-BUF.
pub const REPLAY_PRODUCER_CONTEXT_COUNT: usize = REPLAY_ENCODER_PIPELINE_DEPTH + 1;
pub const MAX_MESSAGE_BYTES: usize =
    HEADER_BYTES + FRAME_BATCH_PREFIX_BYTES + 8 * MAX_FRAME_INTERVALS;

const MAGIC: [u8; 8] = *b"RDCAP001";
const HEADER_BYTES: usize = 32;
const HELLO_BYTES: usize = 16;
const FRAME_BATCH_PREFIX_BYTES: usize = 16;
const GOODBYE_BYTES: usize = 16;
const REPLAY_SOURCE_CANDIDATE_BYTES: usize = 16;
const REPLAY_SOURCE_REJECTED_BYTES: usize = 8;
const REPLAY_FRAME_COPIED_BYTES: usize = 32;
const REPLAY_FRAME_EXPORTED_BYTES: usize = 56;
const REPLAY_FRAME_RELEASED_BYTES: usize = 16;
const OVERLAY_STATUS_BYTES: usize = 8;

const KIND_HELLO: u8 = 1;
const KIND_FRAME_BATCH: u8 = 2;
const KIND_GOODBYE: u8 = 3;
const KIND_REPLAY_SOURCE_CANDIDATE: u8 = 4;
const KIND_REPLAY_SOURCE_REJECTED: u8 = 5;
const KIND_REPLAY_FRAME_COPIED: u8 = 6;
const KIND_OVERLAY_STATUS: u8 = 7;
const KIND_REPLAY_FRAME_EXPORTED: u8 = 8;
const KIND_REPLAY_FRAME_RELEASED: u8 = 9;

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct CaptureSessionId([u8; 16]);

impl CaptureSessionId {
    /// Construct a non-zero session identifier generated by the daemon.
    ///
    /// # Errors
    ///
    /// Returns [`ProtocolError`] when every byte is zero.
    pub fn new(bytes: [u8; 16]) -> Result<Self, ProtocolError> {
        if bytes == [0; 16] {
            return Err(ProtocolError::new("capture session id cannot be zero"));
        }
        Ok(Self(bytes))
    }

    #[must_use]
    pub const fn as_bytes(self) -> [u8; 16] {
        self.0
    }

    #[must_use]
    pub fn to_hex(self) -> String {
        const HEX: &[u8; 16] = b"0123456789abcdef";
        let mut encoded = String::with_capacity(32);
        for byte in self.0 {
            encoded.push(char::from(HEX[usize::from(byte >> 4)]));
            encoded.push(char::from(HEX[usize::from(byte & 0x0f)]));
        }
        encoded
    }

    /// Parse the canonical 32-character lowercase hexadecimal form used in a
    /// child process environment.
    ///
    /// # Errors
    ///
    /// Returns [`ProtocolError`] for an invalid length, non-lowercase hex, or
    /// the forbidden all-zero identifier.
    pub fn from_hex(value: &str) -> Result<Self, ProtocolError> {
        if value.len() != 32 {
            return Err(ProtocolError::new("capture session id has invalid length"));
        }
        let mut decoded = [0; 16];
        for (index, pair) in value.as_bytes().chunks_exact(2).enumerate() {
            decoded[index] = (decode_hex(pair[0])? << 4) | decode_hex(pair[1])?;
        }
        Self::new(decoded)
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum CaptureApi {
    Vulkan = 1,
}

impl CaptureApi {
    fn from_wire(value: u8) -> Result<Self, ProtocolError> {
        match value {
            1 => Ok(Self::Vulkan),
            _ => Err(ProtocolError::new("unsupported capture API")),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum GoodbyeReason {
    Normal = 1,
    ProcessExit = 2,
    ProducerError = 3,
}

impl GoodbyeReason {
    fn from_wire(value: u8) -> Result<Self, ProtocolError> {
        match value {
            1 => Ok(Self::Normal),
            2 => Ok(Self::ProcessExit),
            3 => Ok(Self::ProducerError),
            _ => Err(ProtocolError::new("unsupported capture goodbye reason")),
        }
    }
}

/// Bounded renderer failures that the Vulkan layer can observe directly.
/// These describe only Redunar's optional overlay; presentation remains
/// fail-open and the game continues normally.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum OverlayFailureReason {
    RequiredVulkanFunctionsUnavailable = 1,
    GraphicsQueueUnavailable = 2,
    RendererCapacityReached = 3,
}

impl OverlayFailureReason {
    fn from_wire(value: u8) -> Result<Self, ProtocolError> {
        match value {
            1 => Ok(Self::RequiredVulkanFunctionsUnavailable),
            2 => Ok(Self::GraphicsQueueUnavailable),
            3 => Ok(Self::RendererCapacityReached),
            _ => Err(ProtocolError::new("overlay failure reason is unsupported")),
        }
    }
}

/// Authoritative overlay state reported by the in-process Vulkan layer.
/// `Active` is emitted only after an overlay command buffer was submitted.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OverlayRuntimeStatus {
    Requested,
    Active,
    Error(OverlayFailureReason),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum ReplayPixelFormat {
    Rgba8Unorm = 1,
    Rgba8Srgb = 2,
    Bgra8Unorm = 3,
    Bgra8Srgb = 4,
    A2b10g10r10Unorm = 5,
    A2r10g10b10Unorm = 6,
}

impl ReplayPixelFormat {
    fn from_wire(value: u8) -> Result<Self, ProtocolError> {
        match value {
            1 => Ok(Self::Rgba8Unorm),
            2 => Ok(Self::Rgba8Srgb),
            3 => Ok(Self::Bgra8Unorm),
            4 => Ok(Self::Bgra8Srgb),
            5 => Ok(Self::A2b10g10r10Unorm),
            6 => Ok(Self::A2r10g10b10Unorm),
            _ => Err(ProtocolError::new(
                "replay source pixel format is unsupported",
            )),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ReplaySourceCandidate {
    pub width: u32,
    pub height: u32,
    pub pixel_format: ReplayPixelFormat,
    pub target_frames_per_second: u8,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum ReplaySourceRejection {
    InvalidStructure = 1,
    ProtectedSwapchain = 2,
    ArrayLayersUnsupported = 3,
    TransferSourceUsageMissing = 4,
    DimensionsUnsupported = 5,
    PixelFormatUnsupported = 6,
    ExternalMemoryUnsupported = 7,
    EncoderBackendUnavailable = 8,
    VideoEncodeUnsupported = 9,
}

impl ReplaySourceRejection {
    fn from_wire(value: u8) -> Result<Self, ProtocolError> {
        match value {
            1 => Ok(Self::InvalidStructure),
            2 => Ok(Self::ProtectedSwapchain),
            3 => Ok(Self::ArrayLayersUnsupported),
            4 => Ok(Self::TransferSourceUsageMissing),
            5 => Ok(Self::DimensionsUnsupported),
            6 => Ok(Self::PixelFormatUnsupported),
            7 => Ok(Self::ExternalMemoryUnsupported),
            8 => Ok(Self::EncoderBackendUnavailable),
            9 => Ok(Self::VideoEncodeUnsupported),
            _ => Err(ProtocolError::new(
                "replay source rejection reason is unsupported",
            )),
        }
    }
}

impl ReplaySourceCandidate {
    fn validate(self) -> Result<(), ProtocolError> {
        if self.width == 0
            || self.height == 0
            || self.width > MAX_REPLAY_SOURCE_WIDTH
            || self.height > MAX_REPLAY_SOURCE_HEIGHT
        {
            return Err(ProtocolError::new("replay source dimensions are invalid"));
        }
        if !matches!(self.target_frames_per_second, 30 | 60 | 120) {
            return Err(ProtocolError::new("replay source frame rate is invalid"));
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CaptureMessage {
    Hello {
        session_id: CaptureSessionId,
        process_id: u32,
        api: CaptureApi,
        producer_started_monotonic_ns: u64,
    },
    FrameBatch {
        session_id: CaptureSessionId,
        first_sequence: u64,
        frame_intervals_ns: Vec<u64>,
    },
    Goodbye {
        session_id: CaptureSessionId,
        last_sequence: u64,
        reason: GoodbyeReason,
    },
    /// Metadata-only candidate. Raw pixels and encoded packets are forbidden
    /// from this bounded datagram protocol.
    ReplaySourceCandidate {
        session_id: CaptureSessionId,
        candidate: ReplaySourceCandidate,
    },
    ReplaySourceRejected {
        session_id: CaptureSessionId,
        reason: ReplaySourceRejection,
    },
    /// Bounded proof that one swapchain image reached Redunar-owned mapped
    /// memory. Pixel bytes never enter this datagram protocol.
    ReplayFrameCopied {
        session_id: CaptureSessionId,
        sequence: u64,
        source: ReplaySourceCandidate,
        copied_bytes: u32,
        sample_checksum: u64,
    },
    /// Metadata for one GPU-backed exported frame. The FD number is meaningful
    /// only in the producer process identified by `Hello`; no pixels cross
    /// this datagram protocol.
    ReplayFrameExported {
        session_id: CaptureSessionId,
        sequence: u64,
        fd_number: u32,
        source: ReplaySourceCandidate,
        offset: u32,
        stride: u32,
        modifier: u64,
        timestamp_ns: u64,
        duration_ns: u64,
    },
    /// Daemon-to-producer release token. It permits a producer-side export
    /// slot to be reused only after the daemon has finished importing it.
    ReplayFrameReleased {
        session_id: CaptureSessionId,
        sequence: u64,
    },
    OverlayStatus {
        session_id: CaptureSessionId,
        status: OverlayRuntimeStatus,
    },
}

impl CaptureMessage {
    #[must_use]
    pub const fn session_id(&self) -> CaptureSessionId {
        match self {
            Self::Hello { session_id, .. }
            | Self::FrameBatch { session_id, .. }
            | Self::Goodbye { session_id, .. }
            | Self::ReplaySourceCandidate { session_id, .. }
            | Self::ReplaySourceRejected { session_id, .. }
            | Self::ReplayFrameCopied { session_id, .. }
            | Self::ReplayFrameExported { session_id, .. }
            | Self::ReplayFrameReleased { session_id, .. }
            | Self::OverlayStatus { session_id, .. } => *session_id,
        }
    }
}

/// Encode one message into caller-owned storage so capture producers do not
/// need to allocate on the presentation path.
///
/// # Errors
///
/// Returns [`ProtocolError`] for invalid frame batches or insufficient output
/// storage.
pub fn encode_message(message: &CaptureMessage, output: &mut [u8]) -> Result<usize, ProtocolError> {
    let (kind, payload_bytes) = message_layout(message)?;
    let message_bytes = HEADER_BYTES + payload_bytes;
    if message_bytes > MAX_MESSAGE_BYTES {
        return Err(ProtocolError::new("capture message exceeds protocol limit"));
    }
    if output.len() < message_bytes {
        return Err(ProtocolError::new("capture output buffer is too small"));
    }

    output[..message_bytes].fill(0);
    output[..8].copy_from_slice(&MAGIC);
    write_u16(output, 8, PROTOCOL_VERSION);
    output[10] = kind;
    let payload_bytes = u16::try_from(payload_bytes)
        .map_err(|_| ProtocolError::new("capture payload length exceeds wire field"))?;
    write_u16(output, 12, payload_bytes);
    output[16..32].copy_from_slice(&message.session_id().as_bytes());

    encode_payload(message, output)?;
    Ok(message_bytes)
}

fn message_layout(message: &CaptureMessage) -> Result<(u8, usize), ProtocolError> {
    let layout = match message {
        CaptureMessage::Hello { .. } => (KIND_HELLO, HELLO_BYTES),
        CaptureMessage::FrameBatch {
            frame_intervals_ns, ..
        } => {
            validate_intervals(frame_intervals_ns)?;
            (
                KIND_FRAME_BATCH,
                FRAME_BATCH_PREFIX_BYTES + frame_intervals_ns.len() * 8,
            )
        }
        CaptureMessage::Goodbye { .. } => (KIND_GOODBYE, GOODBYE_BYTES),
        CaptureMessage::ReplaySourceCandidate { candidate, .. } => {
            candidate.validate()?;
            (KIND_REPLAY_SOURCE_CANDIDATE, REPLAY_SOURCE_CANDIDATE_BYTES)
        }
        CaptureMessage::ReplaySourceRejected { .. } => {
            (KIND_REPLAY_SOURCE_REJECTED, REPLAY_SOURCE_REJECTED_BYTES)
        }
        CaptureMessage::ReplayFrameCopied {
            source,
            copied_bytes,
            ..
        } => {
            source.validate()?;
            validate_copied_bytes(*source, *copied_bytes)?;
            (KIND_REPLAY_FRAME_COPIED, REPLAY_FRAME_COPIED_BYTES)
        }
        CaptureMessage::ReplayFrameExported {
            fd_number,
            source,
            offset,
            stride,
            modifier: _,
            timestamp_ns,
            duration_ns,
            ..
        } => {
            source.validate()?;
            validate_exported_frame(*fd_number, *offset, *stride, *timestamp_ns, *duration_ns)?;
            (KIND_REPLAY_FRAME_EXPORTED, REPLAY_FRAME_EXPORTED_BYTES)
        }
        CaptureMessage::ReplayFrameReleased { .. } => {
            (KIND_REPLAY_FRAME_RELEASED, REPLAY_FRAME_RELEASED_BYTES)
        }
        CaptureMessage::OverlayStatus { .. } => (KIND_OVERLAY_STATUS, OVERLAY_STATUS_BYTES),
    };
    Ok(layout)
}

fn encode_payload(message: &CaptureMessage, output: &mut [u8]) -> Result<(), ProtocolError> {
    match message {
        CaptureMessage::Hello {
            process_id,
            api,
            producer_started_monotonic_ns,
            ..
        } => {
            write_u32(output, HEADER_BYTES, *process_id);
            output[HEADER_BYTES + 4] = *api as u8;
            write_u64(output, HEADER_BYTES + 8, *producer_started_monotonic_ns);
        }
        CaptureMessage::FrameBatch {
            first_sequence,
            frame_intervals_ns,
            ..
        } => {
            write_u64(output, HEADER_BYTES, *first_sequence);
            let frame_count = u16::try_from(frame_intervals_ns.len())
                .map_err(|_| ProtocolError::new("capture frame count exceeds wire field"))?;
            write_u16(output, HEADER_BYTES + 8, frame_count);
            for (index, interval) in frame_intervals_ns.iter().enumerate() {
                write_u64(
                    output,
                    HEADER_BYTES + FRAME_BATCH_PREFIX_BYTES + index * 8,
                    *interval,
                );
            }
        }
        CaptureMessage::Goodbye {
            last_sequence,
            reason,
            ..
        } => {
            write_u64(output, HEADER_BYTES, *last_sequence);
            output[HEADER_BYTES + 8] = *reason as u8;
        }
        CaptureMessage::ReplaySourceCandidate { candidate, .. } => {
            write_u32(output, HEADER_BYTES, candidate.width);
            write_u32(output, HEADER_BYTES + 4, candidate.height);
            output[HEADER_BYTES + 8] = candidate.pixel_format as u8;
            output[HEADER_BYTES + 9] = candidate.target_frames_per_second;
        }
        CaptureMessage::ReplaySourceRejected { reason, .. } => {
            output[HEADER_BYTES] = *reason as u8;
        }
        CaptureMessage::ReplayFrameCopied {
            sequence,
            source,
            copied_bytes,
            sample_checksum,
            ..
        } => {
            encode_replay_frame_copied(output, *sequence, *source, *copied_bytes, *sample_checksum);
        }
        CaptureMessage::ReplayFrameExported {
            sequence,
            fd_number,
            source,
            offset,
            stride,
            modifier,
            timestamp_ns,
            duration_ns,
            ..
        } => {
            let base = HEADER_BYTES;
            write_u64(output, base, *sequence);
            write_u32(output, base + 8, *fd_number);
            write_u32(output, base + 12, source.width);
            write_u32(output, base + 16, source.height);
            output[base + 20] = source.pixel_format as u8;
            output[base + 21] = source.target_frames_per_second;
            write_u32(output, base + 24, *offset);
            write_u32(output, base + 28, *stride);
            write_u64(output, base + 32, *modifier);
            write_u64(output, base + 40, *timestamp_ns);
            // Duration is carried in the fixed trailing field by reusing the
            // message's reserved extension area in protocol v5.
            write_u64(output, base + 48, *duration_ns);
        }
        CaptureMessage::ReplayFrameReleased { sequence, .. } => {
            write_u64(output, HEADER_BYTES, *sequence);
        }
        CaptureMessage::OverlayStatus { status, .. } => {
            let (state, reason) = match status {
                OverlayRuntimeStatus::Requested => (1, 0),
                OverlayRuntimeStatus::Active => (2, 0),
                OverlayRuntimeStatus::Error(reason) => (3, *reason as u8),
            };
            output[HEADER_BYTES] = state;
            output[HEADER_BYTES + 1] = reason;
        }
    }
    Ok(())
}

fn encode_replay_frame_copied(
    output: &mut [u8],
    sequence: u64,
    source: ReplaySourceCandidate,
    copied_bytes: u32,
    sample_checksum: u64,
) {
    write_u64(output, HEADER_BYTES, sequence);
    write_u32(output, HEADER_BYTES + 8, copied_bytes);
    write_u32(output, HEADER_BYTES + 12, source.width);
    write_u32(output, HEADER_BYTES + 16, source.height);
    output[HEADER_BYTES + 20] = source.pixel_format as u8;
    output[HEADER_BYTES + 21] = source.target_frames_per_second;
    write_u64(output, HEADER_BYTES + 24, sample_checksum);
}

/// Encode a frame batch directly from a borrowed slice. Capture layers use
/// this form to avoid allocating a `Vec` when a fixed producer buffer fills.
///
/// # Errors
///
/// Returns [`ProtocolError`] for an empty/oversized/zero-valued batch or an
/// insufficient output buffer.
pub fn encode_frame_batch(
    session_id: CaptureSessionId,
    first_sequence: u64,
    frame_intervals_ns: &[u64],
    output: &mut [u8],
) -> Result<usize, ProtocolError> {
    validate_intervals(frame_intervals_ns)?;
    let payload_bytes = FRAME_BATCH_PREFIX_BYTES + frame_intervals_ns.len() * 8;
    let message_bytes = HEADER_BYTES + payload_bytes;
    if output.len() < message_bytes {
        return Err(ProtocolError::new("capture output buffer is too small"));
    }

    output[..message_bytes].fill(0);
    output[..8].copy_from_slice(&MAGIC);
    write_u16(output, 8, PROTOCOL_VERSION);
    output[10] = KIND_FRAME_BATCH;
    let payload_bytes = u16::try_from(payload_bytes)
        .map_err(|_| ProtocolError::new("capture payload length exceeds wire field"))?;
    let frame_count = u16::try_from(frame_intervals_ns.len())
        .map_err(|_| ProtocolError::new("capture frame count exceeds wire field"))?;
    write_u16(output, 12, payload_bytes);
    output[16..32].copy_from_slice(&session_id.as_bytes());
    write_u64(output, HEADER_BYTES, first_sequence);
    write_u16(output, HEADER_BYTES + 8, frame_count);
    for (index, interval) in frame_intervals_ns.iter().enumerate() {
        write_u64(
            output,
            HEADER_BYTES + FRAME_BATCH_PREFIX_BYTES + index * 8,
            *interval,
        );
    }
    Ok(message_bytes)
}

/// Decode one complete local capture message.
///
/// # Errors
///
/// Returns [`ProtocolError`] when the message is truncated, oversized,
/// unsupported, non-canonical, or contains invalid frame intervals.
pub fn decode_message(input: &[u8]) -> Result<CaptureMessage, ProtocolError> {
    let (kind, payload_bytes, session_id) = decode_header(input)?;

    match kind {
        KIND_HELLO if payload_bytes == HELLO_BYTES => Ok(CaptureMessage::Hello {
            session_id,
            process_id: read_u32(input, HEADER_BYTES),
            api: CaptureApi::from_wire(input[HEADER_BYTES + 4])?,
            producer_started_monotonic_ns: read_u64(input, HEADER_BYTES + 8),
        }),
        KIND_FRAME_BATCH if payload_bytes >= FRAME_BATCH_PREFIX_BYTES => {
            decode_frame_batch(input, session_id, payload_bytes)
        }
        KIND_GOODBYE if payload_bytes == GOODBYE_BYTES => decode_goodbye(input, session_id),
        KIND_REPLAY_SOURCE_CANDIDATE if payload_bytes == REPLAY_SOURCE_CANDIDATE_BYTES => {
            decode_replay_source_candidate(input, session_id)
        }
        KIND_REPLAY_SOURCE_REJECTED if payload_bytes == REPLAY_SOURCE_REJECTED_BYTES => {
            decode_replay_source_rejection(input, session_id)
        }
        KIND_REPLAY_FRAME_COPIED if payload_bytes == REPLAY_FRAME_COPIED_BYTES => {
            decode_replay_frame_copied(input, session_id)
        }
        KIND_REPLAY_FRAME_EXPORTED if payload_bytes == REPLAY_FRAME_EXPORTED_BYTES => {
            decode_replay_frame_exported(input, session_id)
        }
        KIND_REPLAY_FRAME_RELEASED if payload_bytes == REPLAY_FRAME_RELEASED_BYTES => {
            if input[HEADER_BYTES + 8..HEADER_BYTES + REPLAY_FRAME_RELEASED_BYTES]
                .iter()
                .any(|byte| *byte != 0)
            {
                return Err(ProtocolError::new(
                    "replay frame release reserved fields are non-zero",
                ));
            }
            Ok(CaptureMessage::ReplayFrameReleased {
                session_id,
                sequence: read_u64(input, HEADER_BYTES),
            })
        }
        KIND_OVERLAY_STATUS if payload_bytes == OVERLAY_STATUS_BYTES => {
            decode_overlay_status(input, session_id)
        }
        KIND_HELLO
        | KIND_FRAME_BATCH
        | KIND_GOODBYE
        | KIND_REPLAY_SOURCE_CANDIDATE
        | KIND_REPLAY_SOURCE_REJECTED
        | KIND_REPLAY_FRAME_COPIED
        | KIND_REPLAY_FRAME_EXPORTED
        | KIND_REPLAY_FRAME_RELEASED
        | KIND_OVERLAY_STATUS => Err(ProtocolError::new(
            "capture message payload has invalid size",
        )),
        _ => Err(ProtocolError::new("capture message kind is unsupported")),
    }
}

fn decode_header(input: &[u8]) -> Result<(u8, usize, CaptureSessionId), ProtocolError> {
    if input.len() < HEADER_BYTES {
        return Err(ProtocolError::new("capture message is truncated"));
    }
    if input.len() > MAX_MESSAGE_BYTES {
        return Err(ProtocolError::new("capture message exceeds protocol limit"));
    }
    if input[..8] != MAGIC {
        return Err(ProtocolError::new("capture message has invalid magic"));
    }
    if read_u16(input, 8) != PROTOCOL_VERSION {
        return Err(ProtocolError::new(
            "capture protocol version is unsupported",
        ));
    }
    if input[11] != 0 || read_u16(input, 14) != 0 {
        return Err(ProtocolError::new(
            "capture message reserved fields are non-zero",
        ));
    }
    let payload_bytes = usize::from(read_u16(input, 12));
    if input.len() != HEADER_BYTES + payload_bytes {
        return Err(ProtocolError::new(
            "capture message length does not match header",
        ));
    }
    let mut session_bytes = [0; 16];
    session_bytes.copy_from_slice(&input[16..32]);
    let session_id = CaptureSessionId::new(session_bytes)?;
    Ok((input[10], payload_bytes, session_id))
}

fn decode_frame_batch(
    input: &[u8],
    session_id: CaptureSessionId,
    payload_bytes: usize,
) -> Result<CaptureMessage, ProtocolError> {
    if input[HEADER_BYTES + 10..HEADER_BYTES + FRAME_BATCH_PREFIX_BYTES]
        .iter()
        .any(|byte| *byte != 0)
    {
        return Err(ProtocolError::new(
            "capture frame batch reserved fields are non-zero",
        ));
    }
    let count = usize::from(read_u16(input, HEADER_BYTES + 8));
    if payload_bytes != FRAME_BATCH_PREFIX_BYTES + count * 8 {
        return Err(ProtocolError::new(
            "capture frame batch count does not match payload",
        ));
    }
    let mut intervals = Vec::with_capacity(count);
    for index in 0..count {
        intervals.push(read_u64(
            input,
            HEADER_BYTES + FRAME_BATCH_PREFIX_BYTES + index * 8,
        ));
    }
    validate_intervals(&intervals)?;
    Ok(CaptureMessage::FrameBatch {
        session_id,
        first_sequence: read_u64(input, HEADER_BYTES),
        frame_intervals_ns: intervals,
    })
}

fn decode_goodbye(
    input: &[u8],
    session_id: CaptureSessionId,
) -> Result<CaptureMessage, ProtocolError> {
    if input[HEADER_BYTES + 9..HEADER_BYTES + GOODBYE_BYTES]
        .iter()
        .any(|byte| *byte != 0)
    {
        return Err(ProtocolError::new(
            "capture goodbye reserved fields are non-zero",
        ));
    }
    Ok(CaptureMessage::Goodbye {
        session_id,
        last_sequence: read_u64(input, HEADER_BYTES),
        reason: GoodbyeReason::from_wire(input[HEADER_BYTES + 8])?,
    })
}

fn decode_overlay_status(
    input: &[u8],
    session_id: CaptureSessionId,
) -> Result<CaptureMessage, ProtocolError> {
    if input[HEADER_BYTES + 2..HEADER_BYTES + OVERLAY_STATUS_BYTES]
        .iter()
        .any(|byte| *byte != 0)
    {
        return Err(ProtocolError::new(
            "overlay status reserved fields are non-zero",
        ));
    }
    let status = match (input[HEADER_BYTES], input[HEADER_BYTES + 1]) {
        (1, 0) => OverlayRuntimeStatus::Requested,
        (2, 0) => OverlayRuntimeStatus::Active,
        (3, reason) => OverlayRuntimeStatus::Error(OverlayFailureReason::from_wire(reason)?),
        _ => return Err(ProtocolError::new("overlay status is invalid")),
    };
    Ok(CaptureMessage::OverlayStatus { session_id, status })
}

fn decode_replay_frame_copied(
    input: &[u8],
    session_id: CaptureSessionId,
) -> Result<CaptureMessage, ProtocolError> {
    if input[HEADER_BYTES + 22..HEADER_BYTES + 24]
        .iter()
        .any(|byte| *byte != 0)
    {
        return Err(ProtocolError::new(
            "replay frame copy reserved fields are non-zero",
        ));
    }
    let copied_bytes = read_u32(input, HEADER_BYTES + 8);
    let source = ReplaySourceCandidate {
        width: read_u32(input, HEADER_BYTES + 12),
        height: read_u32(input, HEADER_BYTES + 16),
        pixel_format: ReplayPixelFormat::from_wire(input[HEADER_BYTES + 20])?,
        target_frames_per_second: input[HEADER_BYTES + 21],
    };
    source.validate()?;
    validate_copied_bytes(source, copied_bytes)?;
    Ok(CaptureMessage::ReplayFrameCopied {
        session_id,
        sequence: read_u64(input, HEADER_BYTES),
        source,
        copied_bytes,
        sample_checksum: read_u64(input, HEADER_BYTES + 24),
    })
}

fn decode_replay_frame_exported(
    input: &[u8],
    session_id: CaptureSessionId,
) -> Result<CaptureMessage, ProtocolError> {
    let base = HEADER_BYTES;
    if input[base + 22..base + 24].iter().any(|byte| *byte != 0) {
        return Err(ProtocolError::new(
            "replay frame export reserved fields are non-zero",
        ));
    }
    let source = ReplaySourceCandidate {
        width: read_u32(input, base + 12),
        height: read_u32(input, base + 16),
        pixel_format: ReplayPixelFormat::from_wire(input[base + 20])?,
        target_frames_per_second: input[base + 21],
    };
    let fd_number = read_u32(input, base + 8);
    let offset = read_u32(input, base + 24);
    let stride = read_u32(input, base + 28);
    let modifier = read_u64(input, base + 32);
    let timestamp_ns = read_u64(input, base + 40);
    let duration_ns = read_u64(input, base + 48);
    source.validate()?;
    validate_exported_frame(fd_number, offset, stride, timestamp_ns, duration_ns)?;
    Ok(CaptureMessage::ReplayFrameExported {
        session_id,
        sequence: read_u64(input, base),
        fd_number,
        source,
        offset,
        stride,
        modifier,
        timestamp_ns,
        duration_ns,
    })
}

fn validate_exported_frame(
    fd_number: u32,
    offset: u32,
    stride: u32,
    timestamp_ns: u64,
    duration_ns: u64,
) -> Result<(), ProtocolError> {
    if !(3..=1_000_000).contains(&fd_number) {
        return Err(ProtocolError::new("replay export FD number is invalid"));
    }
    if stride == 0 || stride > MAX_REPLAY_SOURCE_WIDTH.saturating_mul(4) {
        return Err(ProtocolError::new("replay export stride is invalid"));
    }
    if duration_ns == 0 || duration_ns > 1_000_000_000 {
        return Err(ProtocolError::new("replay export duration is invalid"));
    }
    if timestamp_ns.checked_add(duration_ns).is_none() {
        return Err(ProtocolError::new("replay export timestamp overflows"));
    }
    let _ = offset;
    Ok(())
}

fn validate_copied_bytes(
    source: ReplaySourceCandidate,
    copied_bytes: u32,
) -> Result<(), ProtocolError> {
    let expected = source
        .width
        .checked_mul(source.height)
        .and_then(|pixels| pixels.checked_mul(4))
        .ok_or_else(|| ProtocolError::new("replay copied byte count overflowed"))?;
    if copied_bytes != expected {
        return Err(ProtocolError::new(
            "replay copied byte count does not match its source",
        ));
    }
    Ok(())
}

fn decode_replay_source_rejection(
    input: &[u8],
    session_id: CaptureSessionId,
) -> Result<CaptureMessage, ProtocolError> {
    if input[HEADER_BYTES + 1..HEADER_BYTES + REPLAY_SOURCE_REJECTED_BYTES]
        .iter()
        .any(|byte| *byte != 0)
    {
        return Err(ProtocolError::new(
            "replay source rejection reserved fields are non-zero",
        ));
    }
    Ok(CaptureMessage::ReplaySourceRejected {
        session_id,
        reason: ReplaySourceRejection::from_wire(input[HEADER_BYTES])?,
    })
}

fn decode_replay_source_candidate(
    input: &[u8],
    session_id: CaptureSessionId,
) -> Result<CaptureMessage, ProtocolError> {
    if input[HEADER_BYTES + 10..HEADER_BYTES + REPLAY_SOURCE_CANDIDATE_BYTES]
        .iter()
        .any(|byte| *byte != 0)
    {
        return Err(ProtocolError::new(
            "replay source reserved fields are non-zero",
        ));
    }
    let candidate = ReplaySourceCandidate {
        width: read_u32(input, HEADER_BYTES),
        height: read_u32(input, HEADER_BYTES + 4),
        pixel_format: ReplayPixelFormat::from_wire(input[HEADER_BYTES + 8])?,
        target_frames_per_second: input[HEADER_BYTES + 9],
    };
    candidate.validate()?;
    Ok(CaptureMessage::ReplaySourceCandidate {
        session_id,
        candidate,
    })
}

fn validate_intervals(intervals: &[u64]) -> Result<(), ProtocolError> {
    if intervals.is_empty() {
        return Err(ProtocolError::new("capture frame batch cannot be empty"));
    }
    if intervals.len() > MAX_FRAME_INTERVALS {
        return Err(ProtocolError::new(
            "capture frame batch exceeds protocol limit",
        ));
    }
    if intervals.contains(&0) {
        return Err(ProtocolError::new(
            "capture frame intervals must be greater than zero",
        ));
    }
    Ok(())
}

fn decode_hex(value: u8) -> Result<u8, ProtocolError> {
    match value {
        b'0'..=b'9' => Ok(value - b'0'),
        b'a'..=b'f' => Ok(value - b'a' + 10),
        _ => Err(ProtocolError::new(
            "capture session id is not canonical lowercase hex",
        )),
    }
}

fn write_u16(output: &mut [u8], offset: usize, value: u16) {
    output[offset..offset + 2].copy_from_slice(&value.to_le_bytes());
}

fn write_u32(output: &mut [u8], offset: usize, value: u32) {
    output[offset..offset + 4].copy_from_slice(&value.to_le_bytes());
}

fn write_u64(output: &mut [u8], offset: usize, value: u64) {
    output[offset..offset + 8].copy_from_slice(&value.to_le_bytes());
}

fn read_u16(input: &[u8], offset: usize) -> u16 {
    u16::from_le_bytes(input[offset..offset + 2].try_into().expect("validated u16"))
}

fn read_u32(input: &[u8], offset: usize) -> u32 {
    u32::from_le_bytes(input[offset..offset + 4].try_into().expect("validated u32"))
}

fn read_u64(input: &[u8], offset: usize) -> u64 {
    u64::from_le_bytes(input[offset..offset + 8].try_into().expect("validated u64"))
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProtocolError {
    message: &'static str,
}

impl ProtocolError {
    const fn new(message: &'static str) -> Self {
        Self { message }
    }
}

impl fmt::Display for ProtocolError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.message)
    }
}

impl Error for ProtocolError {}

#[cfg(test)]
mod tests {
    use super::*;

    fn session_id() -> CaptureSessionId {
        CaptureSessionId::new([7; 16]).expect("non-zero session")
    }

    fn round_trip(message: &CaptureMessage) {
        let mut bytes = [0; MAX_MESSAGE_BYTES];
        let length = encode_message(message, &mut bytes).expect("encode message");
        assert_eq!(
            decode_message(&bytes[..length]).expect("decode message"),
            *message
        );
    }

    #[test]
    fn every_message_kind_round_trips() {
        round_trip(&CaptureMessage::Hello {
            session_id: session_id(),
            process_id: 42,
            api: CaptureApi::Vulkan,
            producer_started_monotonic_ns: 9_000,
        });
        round_trip(&CaptureMessage::FrameBatch {
            session_id: session_id(),
            first_sequence: 11,
            frame_intervals_ns: vec![16_000_000, 17_000_000],
        });
        round_trip(&CaptureMessage::Goodbye {
            session_id: session_id(),
            last_sequence: 12,
            reason: GoodbyeReason::Normal,
        });
        round_trip(&CaptureMessage::ReplaySourceCandidate {
            session_id: session_id(),
            candidate: ReplaySourceCandidate {
                width: 2_560,
                height: 1_440,
                pixel_format: ReplayPixelFormat::Bgra8Srgb,
                target_frames_per_second: 60,
            },
        });
        round_trip(&CaptureMessage::ReplaySourceRejected {
            session_id: session_id(),
            reason: ReplaySourceRejection::TransferSourceUsageMissing,
        });
        round_trip(&CaptureMessage::ReplayFrameCopied {
            session_id: session_id(),
            sequence: 12,
            source: ReplaySourceCandidate {
                width: 640,
                height: 480,
                pixel_format: ReplayPixelFormat::Bgra8Unorm,
                target_frames_per_second: 60,
            },
            copied_bytes: 1_228_800,
            sample_checksum: 0x1234_5678_9abc_def0,
        });
        round_trip(&CaptureMessage::ReplayFrameExported {
            session_id: session_id(),
            sequence: 13,
            fd_number: 17,
            source: ReplaySourceCandidate {
                width: 640,
                height: 480,
                pixel_format: ReplayPixelFormat::Bgra8Unorm,
                target_frames_per_second: 60,
            },
            offset: 0,
            stride: 2_560,
            modifier: 0,
            timestamp_ns: 1_000_000_000,
            duration_ns: 16_666_666,
        });
        round_trip(&CaptureMessage::ReplayFrameReleased {
            session_id: session_id(),
            sequence: 13,
        });
        for status in [
            OverlayRuntimeStatus::Requested,
            OverlayRuntimeStatus::Active,
            OverlayRuntimeStatus::Error(OverlayFailureReason::RequiredVulkanFunctionsUnavailable),
        ] {
            round_trip(&CaptureMessage::OverlayStatus {
                session_id: session_id(),
                status,
            });
        }
    }

    #[test]
    fn overlay_status_rejects_unknown_states_reasons_and_reserved_data() {
        let message = CaptureMessage::OverlayStatus {
            session_id: session_id(),
            status: OverlayRuntimeStatus::Requested,
        };
        let mut bytes = [0; MAX_MESSAGE_BYTES];
        let length = encode_message(&message, &mut bytes).expect("encode overlay status");

        let mut unknown_state = bytes[..length].to_vec();
        unknown_state[HEADER_BYTES] = 9;
        assert!(decode_message(&unknown_state).is_err());

        let mut reason_without_error = bytes[..length].to_vec();
        reason_without_error[HEADER_BYTES + 1] = 1;
        assert!(decode_message(&reason_without_error).is_err());

        let mut reserved = bytes[..length].to_vec();
        reserved[HEADER_BYTES + 2] = 1;
        assert!(decode_message(&reserved).is_err());
    }

    #[test]
    fn encoding_is_bounded_and_requires_caller_storage() {
        let too_many = CaptureMessage::FrameBatch {
            session_id: session_id(),
            first_sequence: 0,
            frame_intervals_ns: vec![1; MAX_FRAME_INTERVALS + 1],
        };
        assert_eq!(
            encode_message(&too_many, &mut [0; MAX_MESSAGE_BYTES])
                .expect_err("oversized batch")
                .to_string(),
            "capture frame batch exceeds protocol limit"
        );

        let hello = CaptureMessage::Hello {
            session_id: session_id(),
            process_id: 1,
            api: CaptureApi::Vulkan,
            producer_started_monotonic_ns: 1,
        };
        assert_eq!(
            encode_message(&hello, &mut [0; 8])
                .expect_err("small output")
                .to_string(),
            "capture output buffer is too small"
        );
    }

    #[test]
    fn borrowed_frame_encoding_matches_message_encoding() {
        let intervals = [8_000_000, 9_000_000, 10_000_000];
        let message = CaptureMessage::FrameBatch {
            session_id: session_id(),
            first_sequence: 7,
            frame_intervals_ns: intervals.to_vec(),
        };
        let mut message_bytes = [0; MAX_MESSAGE_BYTES];
        let mut borrowed_bytes = [0; MAX_MESSAGE_BYTES];
        let message_length = encode_message(&message, &mut message_bytes).expect("encode message");
        let borrowed_length = encode_frame_batch(session_id(), 7, &intervals, &mut borrowed_bytes)
            .expect("encode borrowed batch");
        assert_eq!(borrowed_length, message_length);
        assert_eq!(
            &borrowed_bytes[..borrowed_length],
            &message_bytes[..message_length]
        );
    }

    #[test]
    fn decoding_rejects_non_canonical_and_malformed_messages() {
        let message = CaptureMessage::FrameBatch {
            session_id: session_id(),
            first_sequence: 0,
            frame_intervals_ns: vec![16_000_000],
        };
        let mut bytes = [0; MAX_MESSAGE_BYTES];
        let length = encode_message(&message, &mut bytes).expect("encode message");

        let mut invalid_magic = bytes[..length].to_vec();
        invalid_magic[0] = b'X';
        assert!(decode_message(&invalid_magic).is_err());

        let mut future_version = bytes[..length].to_vec();
        write_u16(&mut future_version, 8, PROTOCOL_VERSION + 1);
        assert!(decode_message(&future_version).is_err());

        let mut bad_length = bytes[..length].to_vec();
        write_u16(&mut bad_length, 12, 0);
        assert!(decode_message(&bad_length).is_err());

        let mut reserved = bytes[..length].to_vec();
        reserved[11] = 1;
        assert!(decode_message(&reserved).is_err());

        let mut zero_interval = bytes[..length].to_vec();
        write_u64(
            &mut zero_interval,
            HEADER_BYTES + FRAME_BATCH_PREFIX_BYTES,
            0,
        );
        assert!(decode_message(&zero_interval).is_err());
    }

    #[test]
    fn replay_source_candidate_is_metadata_only_and_strictly_bounded() {
        for candidate in [
            ReplaySourceCandidate {
                width: 0,
                height: 1_080,
                pixel_format: ReplayPixelFormat::Bgra8Unorm,
                target_frames_per_second: 60,
            },
            ReplaySourceCandidate {
                width: MAX_REPLAY_SOURCE_WIDTH + 1,
                height: 1_080,
                pixel_format: ReplayPixelFormat::Bgra8Unorm,
                target_frames_per_second: 60,
            },
            ReplaySourceCandidate {
                width: 1_920,
                height: 1_080,
                pixel_format: ReplayPixelFormat::Bgra8Unorm,
                target_frames_per_second: 59,
            },
        ] {
            let message = CaptureMessage::ReplaySourceCandidate {
                session_id: session_id(),
                candidate,
            };
            assert!(encode_message(&message, &mut [0; MAX_MESSAGE_BYTES]).is_err());
        }

        let mismatched_copy = CaptureMessage::ReplayFrameCopied {
            session_id: session_id(),
            sequence: 1,
            source: ReplaySourceCandidate {
                width: 640,
                height: 480,
                pixel_format: ReplayPixelFormat::Bgra8Unorm,
                target_frames_per_second: 60,
            },
            copied_bytes: 640 * 480 * 4 - 1,
            sample_checksum: 1,
        };
        assert!(encode_message(&mismatched_copy, &mut [0; MAX_MESSAGE_BYTES]).is_err());
    }

    #[test]
    fn replay_producer_has_one_handoff_beyond_encoder_depth() {
        assert_eq!(REPLAY_ENCODER_PIPELINE_DEPTH, 4);
        assert_eq!(
            REPLAY_PRODUCER_CONTEXT_COUNT,
            REPLAY_ENCODER_PIPELINE_DEPTH + 1
        );
    }

    #[test]
    fn zero_session_ids_are_rejected() {
        assert!(CaptureSessionId::new([0; 16]).is_err());
    }

    #[test]
    fn session_id_hex_is_canonical_and_round_trips() {
        let session = CaptureSessionId::new([
            0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54,
            0x32, 0x10,
        ])
        .expect("session id");
        let encoded = session.to_hex();
        assert_eq!(encoded, "0123456789abcdeffedcba9876543210");
        assert_eq!(CaptureSessionId::from_hex(&encoded), Ok(session));
        assert!(CaptureSessionId::from_hex("0123456789ABCDEFFEDCBA9876543210").is_err());
    }
}
