#!/usr/bin/env python3
"""Generate Redunar's bounded 2x antialiased in-game glyph rasters.

Development-only dependencies: Pillow and Noto Sans Mono Regular. The
installed application embeds only the generated integer coverage table.
"""

from pathlib import Path
import sys

from PIL import Image, ImageDraw, ImageFont


WIDTH = 18
HEIGHT = 24
FONT_SIZE = 26
WORDS = 27
SUPPORTED = b"^~-.%*+/0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
DISPLAY = {ord("^"): "°", ord("~"): "·"}


def packed_glyph(font: ImageFont.FreeTypeFont, byte: int) -> list[int]:
    image = Image.new("L", (WIDTH, HEIGHT), 0)
    draw = ImageDraw.Draw(image)
    character = DISPLAY.get(byte, chr(byte))
    # Noto Sans Mono at 26 px fits this 2x logical cell with an 18 px cap
    # height. The offset preserves the original overlay baseline.
    draw.text((1, -8), character, font=font, fill=255)
    words = [0] * WORDS
    for index, coverage in enumerate(image.get_flattened_data()):
        value = (coverage * 3 + 127) // 255
        words[(index * 2) // 32] |= value << ((index * 2) % 32)
    return words


def generate(font_path: Path) -> str:
    font = ImageFont.truetype(str(font_path), FONT_SIZE)
    lines = [
        "// @generated by tools/generate-overlay-font.py; do not edit by hand.",
        "#[rustfmt::skip]",
        "const fn high_resolution_coverage(byte: u8) -> [u32; COVERAGE_WORDS] {",
        "    match byte {",
    ]
    for byte in SUPPORTED:
        words = packed_glyph(font, byte)
        literal = ", ".join(f"0x{word:08x}" for word in words)
        escaped = "\\'" if byte == ord("'") else chr(byte)
        lines.append(f"        b'{escaped}' => [{literal}],")
    lines.extend(
        [
            "        _ => [0; COVERAGE_WORDS],",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate-overlay-font.py FONT OUTPUT")
    font_path = Path(sys.argv[1])
    output = Path(sys.argv[2])
    output.write_text(generate(font_path), encoding="utf-8")


if __name__ == "__main__":
    main()
