#!/usr/bin/env python3
"""Generate the bounded proportional UI font used by the Replay menu."""

from pathlib import Path
import math
import sys

from PIL import Image, ImageDraw, ImageFont


WIDTH = 18
HEIGHT = 24
FONT_SIZE = 20
WORDS = 27
SUPPORTED = b"-.%*+/0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"


def packed_glyph(font: ImageFont.FreeTypeFont, byte: int) -> list[int]:
    image = Image.new("L", (WIDTH, HEIGHT), 0)
    draw = ImageDraw.Draw(image)
    draw.text((0, -5), chr(byte), font=font, fill=255)
    words = [0] * WORDS
    for index, coverage in enumerate(image.get_flattened_data()):
        value = (coverage * 3 + 127) // 255
        words[(index * 2) // 32] |= value << ((index * 2) % 32)
    return words


def logical_advance(font: ImageFont.FreeTypeFont, byte: int) -> int:
    return max(2, min(10, math.ceil(font.getlength(chr(byte)) / 2)))


def generate(font_path: Path) -> str:
    font = ImageFont.truetype(str(font_path), FONT_SIZE)
    lines = [
        "// @generated by tools/generate-overlay-ui-font.py; do not edit by hand.",
        "#[rustfmt::skip]",
        "const fn ui_high_resolution_coverage(byte: u8) -> [u32; COVERAGE_WORDS] {",
        "    match byte {",
    ]
    for byte in SUPPORTED:
        words = packed_glyph(font, byte)
        literal = ", ".join(f"0x{word:08x}" for word in words)
        lines.append(f"        b'{chr(byte)}' => [{literal}],")
    lines.extend(
        [
            "        _ => [0; COVERAGE_WORDS],",
            "    }",
            "}",
            "",
            "#[allow(clippy::match_same_arms)]",
            "#[rustfmt::skip]",
            "const fn ui_advance(byte: u8) -> i32 {",
            "    match byte {",
            "        b' ' => 4,",
        ]
    )
    for byte in SUPPORTED:
        lines.append(f"        b'{chr(byte)}' => {logical_advance(font, byte)},")
    lines.extend(["        _ => 0,", "    }", "}", ""])
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate-overlay-ui-font.py FONT OUTPUT")
    Path(sys.argv[2]).write_text(generate(Path(sys.argv[1])), encoding="utf-8")


if __name__ == "__main__":
    main()
